/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package npd_visualization_swing_app;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import net.sourceforge.chart2d.Chart2D;
import net.sourceforge.chart2d.Chart2DProperties;
import net.sourceforge.chart2d.Dataset;
import net.sourceforge.chart2d.GraphChart2DProperties;
import net.sourceforge.chart2d.GraphProperties;
import net.sourceforge.chart2d.LBChart2D;
import net.sourceforge.chart2d.LegendProperties;
import net.sourceforge.chart2d.MultiColorsProperties;
import net.sourceforge.chart2d.Object2DProperties;

/**
 *
 * @author enesk
 */
public class app_page extends javax.swing.JFrame {

    int n = 42;
    int x = 4;
    double p = 0.2;
    double q = 0.8;

    /**
     * Creates new form app_page
     *
     * @throws java.io.IOException
     */
    public app_page() throws IOException {
        initComponents();

        double comb = factorial(n - 1) / (factorial(x - 1) * factorial(n - x));
        double res = comb * Math.pow(p, (double) x) * Math.pow(q, (double) n - (double) x);
        System.out.println(res);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setMaximumSize(new java.awt.Dimension(500, 300));
        jLabel1.setMinimumSize(new java.awt.Dimension(500, 3000));
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 300));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Negative Binomial Distribution");

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("r =");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("p =");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("CALCULATE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton1)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(app_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(app_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(app_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(app_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new app_page().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(app_page.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    public static double factorial(int number) {
        double result = 1;

        for (double factor = 2; factor <= number; factor++) {
            result *= factor;
        }

        return result;
    }

    private static Chart2D getChart2D(Dataset barData, Dataset lineData, int range) {

        Object2DProperties object2DProps = new Object2DProperties();
        object2DProps.setObjectTitleText("Negative Binomial Distribution");

        //Configure chart properties
        Chart2DProperties chart2DProps = new Chart2DProperties();
        chart2DProps.setChartDataLabelsPrecision(1);

        //Configure legend properties
        LegendProperties legendProps = new LegendProperties();
        String[] legendLabels
                = {"", ""};
        legendProps.setLegendLabelsTexts(legendLabels);

        //Configure graph chart properties
        GraphChart2DProperties graphChart2DProps = new GraphChart2DProperties();
        String[] labelsAxisLabels = genereteLabels(range);
        graphChart2DProps.setLabelsAxisLabelsTexts(labelsAxisLabels);
        graphChart2DProps.setLabelsAxisTitleText("x");
        graphChart2DProps.setNumbersAxisTitleText("P(X=x)");
        graphChart2DProps.setLabelsAxisTicksAlignment(graphChart2DProps.CENTERED);
        Font font = new Font("Verdana", Font.BOLD, 22);
        graphChart2DProps.setNumbersAxisTitleFontStyle(font.getStyle());
        graphChart2DProps.setLabelsAxisTitleFontStyle(font.getStyle());

        //Configure graph properties for line overlay
        GraphProperties graphPropsLine = new GraphProperties();
        graphPropsLine.setGraphBarsExistence(false);
        graphPropsLine.setGraphLinesExistence(true);
        graphPropsLine.setGraphAllowComponentAlignment(true);

        //Configure dataset for line overlay
        Dataset datasetLine = lineData;
        datasetLine.set(0, 0, 0, 20.0f);
        datasetLine.set(0, 1, 0, 40.0f);
        datasetLine.set(0, 2, 0, 50.0f);
        datasetLine.set(0, 3, 0, 0.0f);

        //Configure graph component colors for line overlay
        MultiColorsProperties multiColorsPropsLine = new MultiColorsProperties();
        multiColorsPropsLine.setColorsType(multiColorsPropsLine.PASTEL);

        //Configure graph properties for bar underlay
        GraphProperties graphPropsBars = new GraphProperties();
        graphPropsBars.setGraphOutlineComponentsExistence(true);
        graphPropsBars.setGraphComponentsAlphaComposite(graphPropsBars.ALPHA_COMPOSITE_MILD);

        //Configure dataset for bar underlay
        Dataset datasetBars = barData;
        datasetBars.set(0, 0, 0, 20.0f);
        datasetBars.set(0, 1, 0, 40.0f);
        datasetBars.set(0, 2, 0, 50.0f);
        datasetBars.set(0, 3, 0, 0.0f);

        //Configure graph component colors for bar underlay
        MultiColorsProperties multiColorsPropsBars = new MultiColorsProperties();

        //Configure chart
        LBChart2D chart2D = new LBChart2D();
        chart2D.setObject2DProperties(object2DProps);
        chart2D.setChart2DProperties(chart2DProps);
        chart2D.setLegendProperties(legendProps);
        chart2D.setGraphChart2DProperties(graphChart2DProps);
        chart2D.addGraphProperties(graphPropsLine);
        chart2D.addDataset(datasetLine);
        chart2D.addMultiColorsProperties(multiColorsPropsLine);
        chart2D.addGraphProperties(graphPropsBars);
        chart2D.addDataset(datasetBars);
        chart2D.addMultiColorsProperties(multiColorsPropsBars);

        //Optional validation:  Prints debug messages if invalid only.
        if (!chart2D.validate(false)) {
            chart2D.validate(true);
        }

        //<-- End Chart2D configuration -->
        return chart2D;
    }

    public static String[] genereteLabels(int range) {
        String[] label = new String[range];

        for (int i = 0; i < range; i++) {
            label[i] = String.valueOf(i);
        }

        return label;
    }

    class drawChart extends Thread {

        Dataset barData, lineData;
        int range;

        public drawChart(Dataset barData, Dataset lineData, int range) {
            this.barData = barData;
            this.lineData = lineData;
            this.range = range;
        }

        @Override
        public void run() {
            Chart2D chart = getChart2D(barData, lineData, range);
            chart.pack();

            Dimension size = new Dimension(500, 300);
            chart.setSize(size);
            chart.setPreferredSize(size);

            BufferedImage chartImage = chart.getImage();

            jLabel1.setIcon(new ImageIcon(chartImage));
        }

    }

}
